### ISSUE TITLE
UI aborting transfers

### ISSUE THREAD

**Issue by ChronicSmoke** [ChainSafe/chainbridge-ui#103] opened 2021-08-23 18:01 UTC
## Expected Behavior

The UI submits the transaction
## Current Behavior

https://user-images.githubusercontent.com/84600919/130494981-3bcb50bf-22b4-4a32-89c6-de3bc4c23858.mp4

![image](https://user-images.githubusercontent.com/84600919/130494846-f3fffb24-6fed-4674-bb1b-15b38064330c.png)

**Comment by P1sar** [comment] 2021-08-24 10:47
closing duplicate of https://github.com/ChainSafe/ChainBridge/issues/700

**Closed by P1sar** 2021-08-24 10:47 UTC
