### ISSUE TITLE
Networks are not displaying correctly in UI 

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-ui#251] opened 2022-06-07 12:52 UTC
When we change networks on Metamask the event that is listening to the network change is not being triggered in the UI. Hence, the UI still displays the same `homeChain` and `destinationChain`

**Comment by wainola** [comment] 2022-06-10 09:42
This issue is going to be close. The event is not being triggered for the `local setup` just because in the `local setup` the `chainId` is the same for both networks. Since there is no real change in the `chainId`, the event is not being trigger so we are not updating the UI. 

This issue only affects the UI working with local setup. In real life networks don't share the same `chainId`. A potencial fix for this, was to try to setup the `homechainConfig` using another attribute rather than `chainId`. The problem is that for initialization of the state in the UI, the connection with Metamask acts as a source of truth, so in a way is unavoidable to use the info that is being provider by it, to setup the `homechainConfig` and `destinationchainConfig`. 

Finally, this issue is only present when you are running the UI connected to the local setup. If we want to avoid this, it would be better to have differents `chainId` for the local setup.

**Closed by wainola** 2022-06-10 09:42 UTC
Labels: Type: Bug
